scripts: fix some wrappers

diff --git a/bin/fzf b/bin/fzf
--- a/bin/fzf
+++ b/bin/fzf
@@ -1,25 +1,26 @@
 #!/bin/sh
 
-# --ansi flag breaks theme, drop it
-#declare -a new_args
-#for arg in "$@"; do
-#  if [[ $arg != "--ansi" ]]; then
-#    new_args+=("$arg")
-#  fi
-#done
+# find real executable
+real_exe_name="fzf"
+OLDPATH="$PATH"
+PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin"
+real_exe="$(which "$real_exe_name")"
+if [ -z "$real_exe" ]; then
+    echo "real ${real_exe_name} executable not found in ${PATH}"
+    exit 1
+fi
+PATH="$OLDPATH"
 
-# add some default args from config file
-#declare -a default_args
-#if [ -f ~/.config/fzf/flags ]; then
-#  while read -r arg; do
-#    if [[ ! "$arg" = \#* ]]; then
-#      default_args+=( "$arg" );
-#    fi
-#  done <~/.config/fzf/flags
-#fi
+if [ -z "$FZF_DEFAULT_COMMAND" ]; then
+    export FZF_DEFAULT_COMMAND="find -maxdepth 6"
+fi
+
+if [ -f ~/.config/fzf/hosts/"${HOST}" ]; then
+    export FZF_DEFAULT_OPTS_FILE=~/.config/fzf/hosts/"${HOST}"
+fi
 
 # beam cursor to make it more intuitive that we're in "insert mode"
 printf '\033[6 q' >/dev/tty
 
-exec /usr/bin/fzf $(cat ~/.config/fzf/flags) "$@"
+exec "$real_exe" "$@"
 
diff --git a/bin/lf b/bin/lf
--- a/bin/lf
+++ b/bin/lf
@@ -1,25 +1,33 @@
 #!/bin/sh
 
+# find real executable
+real_exe_name="lf"
+OLDPATH="$PATH"
+PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin"
+real_exe="$(which "$real_exe_name")"
+if [ -z "$real_exe" ]; then
+    echo "real ${real_exe_name} executable not found in ${PATH}"
+    exit 1
+fi
+PATH="$OLDPATH"
+
+# on termux /tmp is not accessible
 if [ -n "$TMPDIR" ]; then
   export LF_DATA_HOME="${TMPDIR}"
 else
   export LF_DATA_HOME=/tmp
 fi
 
+# lf does not work nicely with tmux-256color
 if [ "$TERM" = "tmux-256color" ]; then
   export OLDTERM="$TERM"
   export TERM="tmux"
 fi
 
-real_lf="$(which -a lf | grep -v "$0" | head -n1)"
-if [ -z "$real_lf" ]; then
-    echo "real lf executable not found, check your PATH"
-    exit 1
-fi
 
 if [ -f ~/.config/lf/hosts/"${HOST}" ]; then
-    exec "$real_lf" -config ~/.config/lf/hosts/"${HOST}" "$@"
+    exec "$real_exe" -config ~/.config/lf/hosts/"${HOST}" "$@"
 else
-    exec "$real_lf" -config ~/.config/lf/lfrc "$@"
+    exec "$real_exe" -config ~/.config/lf/lfrc "$@"
 fi
 
