scripts: detect firefox-bin if firefox not found

diff --git a/bin/open-in-browser b/bin/open-in-browser
--- a/bin/open-in-browser
+++ b/bin/open-in-browser
@@ -2,10 +2,19 @@
 
 [ -z "$1" ] && exit 1
 
+firefox_exe="firefox"
+if ! command -v "$firefox_exe" 1>/dev/null 2>&1; then
+    firefox_exe="firefox-bin"
+fi
+if ! command -v "$firefox_exe" 1>/dev/null 2>&1; then
+    echo "firefox exe not found"
+    exit 1
+fi
+
 if ! pgrep firefox 1>/dev/null 2>&1; then
-    hyprctl dispatch exec -- firefox
+    hyprctl dispatch exec -- "$firefox_exe"
     sleep 1
 fi
 
-firefox --new-tab "$1"
+"$firefox_exe" --new-tab "$1"
 
