scripts: fix run-desktop-file

diff --git a/bin/run-desktop-file b/bin/run-desktop-file
--- a/bin/run-desktop-file
+++ b/bin/run-desktop-file
@@ -1,1 +1,46 @@
-../scripts/run-desktop-file.sh
+#!/bin/sh
+
+background() {
+    (
+        trap '' HUP
+        "$@" </dev/null >/dev/null 2>&1 &
+    )
+}
+
+if [ -z "$1" ]; then
+  echo "you need to specify full path to desktop file or its name"
+  exit 1
+fi
+
+filename="$(realpath "$1")"
+if [ ! -f "$filename" ]; then
+  # try to search for desktop file ourselves if provided path does not exist
+  filename="$(find ~/.local/share/applications/ /usr/share/applications/ -maxdepth 1 -type f -name "$1" -print -quit)"
+  if [ -z "$filename" ]; then
+    echo "$1 not found in ~/.local/share/applications/ /usr/share/applications/"
+    exit 1
+  fi
+fi
+
+is_term="$(grep -m1 -o -Pe '(?<=^Terminal\=).*' "${filename}")"
+exec_line="$(grep -m1 -o -Pe '(?<=^Exec\=).*' "${filename}" | sed 's/%[fFuUdDnNickvm]//g')"
+
+if [ -z "$exec_line" ]; then
+  echo "exec line not found in $filename"
+  exit 1
+fi
+
+if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
+  if [ "$is_term" = "true" ]; then
+    background foot sh -c "$exec_line"
+  else
+    background sh -c "$exec_line"
+  fi
+else
+  if [ "$is_term" = "true" ]; then
+    background foot sh -c "$exec_line"
+  else
+    background sh -c "$exec_line"
+  fi
+fi
+
